Traceback (most recent call last):
  File "/usr/share/miniconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
extract_data('nycflights','data')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-33-eacefd57b421>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mextract_data[0m[0;34m([0m[0;34m'nycflights'[0m[0;34m,[0m[0;34m'data'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-11-c92d4a860b06>[0m in [0;36mextract_data[0;34m(name, where)[0m
[1;32m      7[0m        [0mprint[0m[0;34m([0m[0;34m"Extracting data..."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m        [0mtar_path[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mjoin[0m[0;34m([0m[0mwhere[0m[0;34m,[0m [0mname[0m[0;34m+[0m[0;34m'.tgz'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m        [0;32mwith[0m [0mtarfile[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mtar_path[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0;34m'r:gz'[0m[0;34m)[0m [0;32mas[0m [0mdata[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m           [0mdata[0m[0;34m.[0m[0mextractall[0m[0;34m([0m[0mwhere[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/big-data/lib/python3.7/tarfile.py[0m in [0;36mopen[0;34m(cls, name, mode, fileobj, bufsize, **kwargs)[0m
[1;32m   1589[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1590[0m                 [0;32mraise[0m [0mCompressionError[0m[0;34m([0m[0;34m"unknown compression type %r"[0m [0;34m%[0m [0mcomptype[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1591[0;31m             [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0mname[0m[0;34m,[0m [0mfilemode[0m[0;34m,[0m [0mfileobj[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1592[0m [0;34m[0m[0m
[1;32m   1593[0m         [0;32melif[0m [0;34m"|"[0m [0;32min[0m [0mmode[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/big-data/lib/python3.7/tarfile.py[0m in [0;36mgzopen[0;34m(cls, name, mode, fileobj, compresslevel, **kwargs)[0m
[1;32m   1635[0m [0;34m[0m[0m
[1;32m   1636[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1637[0;31m             [0mfileobj[0m [0;34m=[0m [0mGzipFile[0m[0;34m([0m[0mname[0m[0;34m,[0m [0mmode[0m [0;34m+[0m [0;34m"b"[0m[0;34m,[0m [0mcompresslevel[0m[0;34m,[0m [0mfileobj[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1638[0m         [0;32mexcept[0m [0mOSError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1639[0m             [0;32mif[0m [0mfileobj[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m [0;32mand[0m [0mmode[0m [0;34m==[0m [0;34m'r'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/big-data/lib/python3.7/gzip.py[0m in [0;36m__init__[0;34m(self, filename, mode, compresslevel, fileobj, mtime)[0m
[1;32m    166[0m             [0mmode[0m [0;34m+=[0m [0;34m'b'[0m[0;34m[0m[0;34m[0m[0m
[1;32m    167[0m         [0;32mif[0m [0mfileobj[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 168[0;31m             [0mfileobj[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mmyfileobj[0m [0;34m=[0m [0mbuiltins[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0mmode[0m [0;32mor[0m [0;34m'rb'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    169[0m         [0;32mif[0m [0mfilename[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    170[0m             [0mfilename[0m [0;34m=[0m [0mgetattr[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0;34m'name'[0m[0;34m,[0m [0;34m''[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/nycflights.tgz'
FileNotFoundError: [Errno 2] No such file or directory: 'data/nycflights.tgz'

